export const INITIATE_GET_CALLS_SAGA = 'INITIATE_GET_CALLS_SAGA';
export const UPDATE_CALL_LOG_STATE = 'UPDATE_CALL_LOG_STATE';
export const INITIATE_SINGLE_CALL_SAGA = 'INITIATE_SINGLE_CALL_SAGA';
export const UPDATE_CALL_DETAILS_STATE = 'UPDATE_CALL_DETAILS_STATE';