// Get calls
export const GET_CALLS = 'GET_CALLS';
export const GET_CALLS_SUCCESS = 'GET_CALLS_SUCCESS';
export const GET_CALLS_ERROR = 'GET_CALLS_ERROR';

// Get call
export const GET_CALL = 'GET_CALL';
export const GET_CALL_SUCCESS = 'GET_CALL_SUCCESS';
export const GET_CALL_ERROR = 'GET_CALL_ERROR';

// ARCHIVE call
export const ARCHIVE_CALL = 'ARCHIVE_CALL';
export const ARCHIVE_CALL_SUCCESS = 'ARCHIVE_CALL_SUCCESS';
export const ARCHIVE_CALL_ERROR = 'ARCHIVE_CALL_ERROR';

// ARCHIVE call
export const ARCHIVE_CALLS = 'ARCHIVE_CALLS';
export const ARCHIVE_CALLS_SUCCESS = 'ARCHIVE_CALLS_SUCCESS';
export const ARCHIVE_CALLS_ERROR = 'ARCHIVE_CALLS_ERROR';