// ACTIVITIES-
export const FETCH_ACTIVITIES_ERROR = 'FETCH_ACTIVITIES_ERROR'
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS'

//UPDATES
export const UPDATE_ACTIVITIES_SUCCESS = 'UPDATE_ACTIVITIES_SUCCESS'
export const UPDATE_ACTIVITIES_ERROR = 'UPDATE_ACTIVITIES_ERROR'

//RESET
export const RESET_ACTIVITIES_SUCCESS = 'RESET_ACTIVITIES_SUCCESS'
export const RESET_ACTIVITIES_ERROR = 'RESET_ACTIVITIES_ERROR'

// ACTIVITY
export const FETCH_ACTIVITY_ERROR = 'FETCH_ACTIVITY_ERROR'
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS'

// UPDATE ACTIVITY
export const UPDATE_ACTIVITY_ERROR = 'UPDATE_ACTIVITY_ERROR'
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS'

// Loading
export const IS_LOADING = 'IS_LOADING'
export const IS_LOADED = 'IS_LOADED'

//OPEN DETAILS
export const DETAILS_OPEN = 'DETAILS_OPEN'
export const DETAILS_CLOSE = 'DETAILS-CLOSE'

//NAVIGATION
export const CURRENT_NAV_IS_ALL = 'CURRENT_NAV_IS_ALL'
export const CURRENT_NAV_IS_INBOX = 'CURRENT_NAV_IS_INBOX'
