module.exports = {
  ERROR: 'ERROR',

  GET_ACTIVITIES: 'GET_ACTIVITIES',
  GET_ACTIVITIES_PENDING: 'GET_ACTIVITIES_PENDING',
  GET_ACTIVITIES_SUCCESS: 'GET_ACTIVITIES_SUCCESS',
  GET_ACTIVITIES_ERROR: 'GET_ACTIVITIES_ERROR',

  GET_ACTIVITY: 'GET_ACTIVITY',
  GET_ACTIVITY_PENDING: 'GET_ACTIVITY_PENDING',
  GET_ACTIVITY_SUCCESS: 'GET_ACTIVITY_SUCCESS',
  GET_ACTIVITY_ERROR: 'GET_ACTIVITY_ERROR',

  UPDATE_ACTIVITY: 'UPDATE_ACTIVITY',
  UPDATE_ACTIVITY_PENDING: 'UPDATE_ACTIVITY_PENDING',
  UPDATE_ACTIVITY_SUCCESS: 'UPDATE_ACTIVITY_SUCCESS',
  UPDATE_ACTIVITY_ERROR: 'UPDATE_ACTIVITY_ERROR',
};
