export const FETCH_ACTIVITIES_ERROR = "FETCH_ACTIVITIES_ERROR";
export const FETCH_ACTIVITIES_REQUEST = "FETCH_ACTIVITIES_REQUEST";
export const FETCH_ACTIVITIES_SUCCESS = "FETCH_ACTIVITIES_SUCCESS";

export const FETCH_ACTIVITY_DETAIL_REQUEST = "FETCH_ACTIVITY_DETAIL_REQUEST";
export const FETCH_ACTIVITY_DETAIL_ERROR = "FETCH_ACTIVITY_DETAIL_ERROR";
export const FETCH_ACTIVITY_DETAIL_SUCCESS = "FETCH_ACTIVITY_DETAIL_SUCCESS";
