const GET_ACTIVITIES_REQUEST = 'activity/GET_ACTIVITIES_REQUEST';
const GET_ACTIVITIES_FAILURE = 'activity/GET_ACTIVITIES_FAILURE';
const GET_ACTIVITIES_SUCCESS = 'activity/GET_ACTIVITIES_SUCCESS';
const RESET_ACTIVITIES_REQUEST = 'activity/RESET_ACTIVITIES_REQUEST';
const RESET_ACTIVITIES_FAILURE = 'activity/RESET_ACTIVITIES_FAILURE';
const RESET_ACTIVITIES_SUCCESS = 'activity/RESET_ACTIVITIES_SUCCESS';
const GET_ACTIVITY_REQUEST = 'activity/GET_ACTIVITY_REQUEST';
const GET_ACTIVITY_FAILURE = 'activity/GET_ACTIVITY_FAILURE';
const GET_ACTIVITY_SUCCESS = 'activity/GET_ACTIVITY_SUCCESS';
const UPDATE_ACTIVITY_REQUEST = 'activity/UPDATE_ACTIVITY_REQUEST';
const UPDATE_ACTIVITY_FAILURE = 'activity/UPDATE_ACTIVITY_FAILURE';
const UPDATE_ACTIVITY_SUCCESS = 'activity/UPDATE_ACTIVITY_SUCCESS';
const UPDATE_ACTIVITIES_REQUEST = 'activity/UPDATE_ACTIVITIES_REQUEST';
const UPDATE_ACTIVITIES_FAILURE = 'activity/UPDATE_ACTIVITIES_FAILURE';
const UPDATE_ACTIVITIES_SUCCESS = 'activity/UPDATE_ACTIVITIES_SUCCESS';



export {
    GET_ACTIVITIES_REQUEST,
    GET_ACTIVITIES_FAILURE,
    GET_ACTIVITIES_SUCCESS,
    GET_ACTIVITY_REQUEST,
    GET_ACTIVITY_FAILURE,
    GET_ACTIVITY_SUCCESS,
    RESET_ACTIVITIES_REQUEST,
    RESET_ACTIVITIES_FAILURE,
    RESET_ACTIVITIES_SUCCESS,
    UPDATE_ACTIVITY_REQUEST,
    UPDATE_ACTIVITY_FAILURE,
    UPDATE_ACTIVITY_SUCCESS,
    UPDATE_ACTIVITIES_REQUEST,
    UPDATE_ACTIVITIES_FAILURE,
    UPDATE_ACTIVITIES_SUCCESS,
};